import type { CaseStudyPoweredBy } from "@launchos/db/schema";
import type { CaseStudySeed } from "./portfolio.js";

/**
 * Our own dispatch platform, as a badge on the four taxi builds that run on
 * it. One constant rather than four copies: the logo path and its dimensions
 * change together or not at all.
 *
 * It lives beside the entries that use it rather than in `portfolio.ts`, which
 * imports this file — a value imported the other way would be a runtime cycle
 * and would read as `undefined` in whichever module happened to load first.
 */
export const CABIO: CaseStudyPoweredBy = {
  name: "Cabio",
  url: "https://cabio.cab",
  logo: "/brand/cabio-logo.png",
  logoWidth: 600,
  logoHeight: 156,
};

/**
 * The fifteen client builds, exactly as they read on the marketing site the
 * day this table was created.
 *
 * This is Shoji's copy, written by hand over months, and it is the reason the
 * migration seeds rather than starting the portfolio empty. Nothing here is
 * generated and nothing here should be paraphrased: the Case Study Writer
 * drafts *new* stories, it does not rewrite these.
 */
export const PORTFOLIO_CLIENTS: readonly CaseStudySeed[] = [
  {
    slug: "grays-cabline",
    name: "Grays CabLine",
    clientName: "Grays CabLine",
    sector: "Taxi and airport transfers",
    summary: "Online booking with instant fares, card payment and a dispatch office behind it, for a Thurrock taxi firm.",
    brief: {
      client: "Grays CabLine is a licensed taxi and airport-transfer firm in Grays, Essex — and it is Shoji's own company, run as an owner-driver for nine years. It was the first business LaunchFlow ever built for.",
      problem: "The old WordPress site took bookings by phone and a slow third-party dispatch plugin. Customers wanted a price before they rang, drivers wanted jobs on their phones, and the office wanted to stop retyping everything.",
      built: "A thirty-page site with a four-step booking engine: address lookup, a pricing engine that quotes by distance, vehicle choice, then card, cash or pay-later. Airport pages for Heathrow, Gatwick, Stansted, Luton and Southend. Behind it, a PIN-protected dispatch office for bookings, drivers, pricing and reports, a customer tracking page for every job, and conversion events wired into Google Ads.",
      results: "Ranks on the first page for its local searches, and enquiries and bookings both rose after the move. The dispatch side grew into Cabio, our multi-tenant platform, which the firm now runs on.",
    },
    stack: ["React", "Express", "PostgreSQL", "Square payments", "Google Maps", "Expo", "Coolify"],
    year: 2026,
    url: "https://grayscabline.co.uk",
    screenshots: { desktop: "/work/grays-cabline-desktop.jpg", mobile: "/work/grays-cabline-mobile.jpg" },
    featured: true,
    kind: "client",
    deliveryStatus: "live",
    charity: false,
    poweredBy: CABIO,
    domain: null,
    tagline: null,
    description: null,
    facts: [],
  },
  {
    slug: "lakeside-purfleet-taxis",
    name: "Lakeside & Purfleet Taxis",
    clientName: "Lakeside & Purfleet Taxis Ltd",
    sector: "Taxi",
    summary: "A lead-generation site with a five-step quote form and an admin panel for following every enquiry up.",
    brief: {
      client: "Lakeside & Purfleet Taxis is a taxi operator covering Lakeside, Purfleet and the rest of Thurrock.",
      problem: "They wanted enquiries captured online, around the clock, without taking on a live booking and payment system they were not ready to run.",
      built: "Thirty-odd pages — services, six airport pages, nine area pages — fronted by a five-step quote form that writes straight into a leads database. Staff sign in to filter leads, set a status, add notes, record the quoted price and the driver, and email the customer back from the same screen. A stats dashboard shows the week at a glance.",
      results: "Live on our servers with nightly backups. Enquiry capture with manual follow-up, exactly as briefed, with online payment ready to switch on later.",
    },
    stack: ["React", "Express", "PostgreSQL", "Docker", "Coolify"],
    year: 2026,
    url: "https://lakesidetaxi.co.uk",
    screenshots: { desktop: "/work/lakeside-purfleet-taxis-desktop.jpg", mobile: "/work/lakeside-purfleet-taxis-mobile.jpg" },
    featured: false,
    kind: "client",
    deliveryStatus: "live",
    charity: false,
    poweredBy: CABIO,
    domain: null,
    tagline: null,
    description: null,
    facts: [],
  },
  {
    slug: "ockendon-station-taxis",
    name: "Ockendon Station Taxis",
    clientName: "Ockendon Station Taxis",
    sector: "Taxi",
    summary: "A local taxi site built round station pickups and fixed airport fares, with a step-by-step booking enquiry.",
    brief: {
      client: "Ockendon Station Taxis is a private hire firm working South Ockendon, Aveley, Grays, Chafford Hundred and the rest of Thurrock.",
      problem: "Almost all their work starts with somebody standing at Ockendon Station or planning an early airport run, and almost all of it came in by phone. There was nothing online for the passenger who wants a price before they ring, and nothing at all after hours.",
      built: "A site organised the way the work actually arrives: local journeys, station pickups and airport transfers, each with its own page and its own area pages for the villages around Ockendon. A multi-step booking enquiry asks for the journey type first, then the addresses, dates and passenger count, so a return airport run with a flight number takes the same short form as a trip to the shops. Airport fares are published — Heathrow, Gatwick, Stansted, Luton and London City — so the price question is answered before anybody picks up the phone.",
      results: "Enquiries now arrive around the clock with the journey already described, and the published airport fares do the quoting.",
    },
    stack: ["WordPress", "Fluent Forms", "Cabio", "Google Business Profile"],
    year: 2026,
    url: "https://ockendonstationtaxis.co.uk",
    screenshots: { desktop: "/work/ockendon-station-taxis-desktop.jpg", mobile: "/work/ockendon-station-taxis-mobile.jpg" },
    featured: false,
    kind: "client",
    deliveryStatus: "live",
    charity: false,
    poweredBy: CABIO,
    domain: null,
    tagline: null,
    description: null,
    facts: [],
  },
  {
    slug: "grays-town-taxis",
    name: "Grays Town Taxis",
    clientName: "Grays Town Taxis",
    sector: "Taxi and airport transfers",
    summary: "A fixed-price booking site on Cabio, with live tracking, corporate accounts and the Google Ads that feed it.",
    brief: {
      client: "Grays Town Taxis is Safiullah Mansoor's private hire firm in Grays, running local work, school runs and airport transfers around the clock.",
      problem: "A one-driver-up operator competing with the big Thurrock firms needs to look every bit as solid as they do — instant quotes, fixed airport prices, tracking, card payment — without paying for a dispatch platform priced for a fleet.",
      built: "The site runs on Cabio Solo, our subscription tier for the single operator: the booking engine, the quote, the live tracking link and the card payment are the same ones our fleet customers use, embedded straight into the site. On top of that a marketing site with fixed airport fares to seven airports, service pages for local, corporate, school-run, long-distance and wedding work, an application form for corporate and school accounts with monthly invoicing, and real Google reviews on the page. We run the Google Ads alongside it.",
      results: "Online booking and tracking on a solo operator's budget, with quotes arriving overnight instead of waiting for the phone.",
    },
    stack: ["Cabio", "Google Ads", "Google Business Profile", "Coolify"],
    year: 2026,
    url: "https://graystowntaxis.co.uk",
    screenshots: { desktop: "/work/grays-town-taxis-desktop.jpg", mobile: "/work/grays-town-taxis-mobile.jpg" },
    featured: false,
    kind: "client",
    deliveryStatus: "live",
    charity: false,
    poweredBy: CABIO,
    domain: null,
    tagline: null,
    description: null,
    facts: [],
  },
  {
    slug: "star-grooming",
    name: "Star Grooming",
    clientName: "Star Grooming",
    sector: "Cat grooming",
    summary: "A marketing site and booking form with a back office that reads the inbox, runs live chat and tracks every lead.",
    brief: {
      client: "Star Grooming is a cat-only groomer in Essex, run by Jade.",
      problem: "Enquiries arrived by email, Facebook, text and phone, and some were lost. Jade needed a professional site and one place to see every lead and answer it.",
      built: "A premium site with service, breed and location pages for search, a gallery and reviews, plus an online booking form with photo attachments. The admin dashboard has a lead pipeline (new, contacted, offered, booked), customer records, an inbox that reads and replies to the business email in-app, live chat with an AI assistant that hands over to Jade the moment she replies, and email and SMS alerts.",
      results: "Every enquiry lands in one pipeline with a status, and the AI chat answers the questions Jade used to answer twenty times a day.",
    },
    stack: ["React", "Express", "PostgreSQL", "OpenAI", "Twilio", "Coolify"],
    year: 2026,
    url: "https://starcatgrooming.com",
    screenshots: { desktop: "/work/star-grooming-desktop.jpg", mobile: "/work/star-grooming-mobile.jpg" },
    featured: true,
    kind: "client",
    deliveryStatus: "live",
    charity: false,
    poweredBy: null,
    domain: null,
    tagline: null,
    description: null,
    facts: [],
  },
  {
    slug: "be-gorgeous-by-monika",
    name: "Be Gorgeous by Monika",
    clientName: "Be Gorgeous by Monika",
    sector: "Beauty salon",
    summary: "A salon booking system with a diary, client records, payments and branded confirmation emails.",
    brief: {
      client: "Be Gorgeous by Monika is a beauty and aesthetics salon in Grays, Essex.",
      problem: "Bookings lived in messages and a paper diary. Double bookings happened, reminders were manual, and there was no record of who had what done.",
      built: "A public booking site and a back office: the diary, client records, services, staff, opening hours, payments and notifications. Bookings create and update client records automatically; the bookings table filters, sorts, totals and exports to CSV. Every confirmation and reminder email was rebuilt and can be previewed in one command. The system was then generalised so it can carry more than one salon.",
      results: "Live for the salon, with the diary running the day. Now the base of our salon product.",
    },
    stack: ["React", "Express", "PostgreSQL", "Caddy", "Coolify"],
    year: 2026,
    url: "https://begorgeousbymonika.com",
    screenshots: { desktop: "/work/be-gorgeous-by-monika-desktop.jpg", mobile: "/work/be-gorgeous-by-monika-mobile.jpg" },
    featured: true,
    kind: "client",
    deliveryStatus: "live",
    charity: false,
    poweredBy: null,
    domain: null,
    tagline: null,
    description: null,
    facts: [],
  },
  {
    slug: "thurrock-tuition-academy",
    name: "Thurrock Tuition Academy",
    clientName: "Thurrock Tuition Academy",
    sector: "Private tuition",
    summary: "A landing page, an admin dashboard and a parent portal for a Grays tutoring business.",
    brief: {
      client: "Thurrock Tuition Academy is Khadija's private tutoring business in Grays.",
      problem: "She needed more than a brochure: somewhere to take enquiries, keep track of students and sessions, and let parents see progress and payments.",
      built: "Three surfaces on one app. A public page with subjects, levels, pricing and a WhatsApp booking button. An admin dashboard for enquiries, students, sessions, progress, tasks and payments. A parent portal, gated by sign-in, where each family sees only their own children. Auth is our own, with roles assigned at sign-up.",
      results: "Live at thurrocktuitionacademy.co.uk, and the first site moved from Replit onto our own servers — the lowest-risk one, so the pipeline was proven before the bigger sites followed.",
    },
    stack: ["React", "Express", "PostgreSQL", "Tailwind", "Docker"],
    year: 2026,
    url: "https://thurrocktuitionacademy.co.uk",
    screenshots: { desktop: "/work/thurrock-tuition-academy-desktop.jpg", mobile: "/work/thurrock-tuition-academy-mobile.jpg" },
    featured: false,
    kind: "client",
    deliveryStatus: "in-build",
    charity: false,
    poweredBy: null,
    domain: null,
    tagline: null,
    description: null,
    facts: [],
  },
  {
    slug: "grays-park-masjid",
    name: "Grays Park Masjid",
    clientName: "Grays Park Masjid",
    sector: "Community and charity",
    summary: "A public website, an admin system and a companion app for the local masjid — built free, as charity.",
    brief: {
      client: "Grays Park Masjid is the mosque and community organisation in Grays. It is where Shoji prays, and the work was done for nothing.",
      problem: "Membership, donations and announcements were handled offline. Applicants had no way to check where their membership stood, and prayer times had to be looked up elsewhere.",
      built: "A public site with prayer times, announcements, events, a gallery, a membership form with a status lookup that needs no account, and one-off or recurring donations through Square. An admin dashboard runs the membership approval workflow, all content, staff and volunteers, donation records and notifications. A companion app with prayer times, Qibla, donations and reading is prepared for the stores.",
      results: "Everything the masjid publishes now goes through one dashboard, and donations are taken online. The app is in store submission.",
    },
    stack: ["React", "Express", "PostgreSQL", "Square", "Expo", "Coolify"],
    year: 2026,
    url: "https://graysparkmasjid.org.uk",
    screenshots: { desktop: "/work/grays-park-masjid-desktop.jpg", mobile: "/work/grays-park-masjid-mobile.jpg" },
    featured: false,
    kind: "client",
    deliveryStatus: "live",
    charity: true,
    poweredBy: null,
    domain: null,
    tagline: null,
    description: null,
    facts: [],
  },
  {
    slug: "nexus-education-group",
    name: "Nexus Education Group",
    clientName: "Nexus Education Group",
    sector: "Education consultancy",
    summary: "A study-abroad platform: course directory, applications, document vault, an AI assistant and a staff dashboard.",
    brief: {
      client: "Nexus Education Group helps students from Islamabad, Rawalpindi and Chakwal apply to universities in the UK, USA, Canada, Australia and Europe.",
      problem: "Student intake ran on WhatsApp and spreadsheets. Documents went missing, enquiries arrived at every hour, and nobody could see the pipeline.",
      built: "A course and university directory, application and consultation flows, a document vault for student uploads, and an AI assistant that answers questions and hands over leads. Staff sign in to a dashboard with owner, admin and staff roles and a full audit log. Branded notifications go out for every enquiry, application and upload. A student app talks to the same API.",
      results: "Live and the most actively developed client platform we run, with the marketing site and the student app being merged into one system.",
    },
    stack: ["React", "Express", "PostgreSQL", "Claude API", "Google Places", "Coolify"],
    year: 2026,
    url: "https://nexusedu.co.uk",
    screenshots: { desktop: "/work/nexus-education-group-desktop.jpg", mobile: "/work/nexus-education-group-mobile.jpg" },
    featured: true,
    kind: "client",
    deliveryStatus: "live",
    charity: false,
    poweredBy: null,
    domain: null,
    tagline: null,
    description: null,
    facts: [],
  },
  {
    slug: "mobile-pc-doctor",
    name: "Mobile PC Doctor",
    clientName: "Mobile PC Doctor",
    sector: "Computer repair",
    summary: "A repair-shop system where every job and every message has a running clock, on the web and in an app.",
    brief: {
      client: "Mobile PC Doctor is a computer repair business in Grays — another of our own.",
      problem: "Jobs were lost to unanswered messages, and repairs ran quietly late because nobody was watching a promised date.",
      built: "A booking, job-tracking, messaging and payments system built round one idea: a clock on everything. A response clock runs while a customer waits to hear back; a delivery clock runs from the moment a quote promises a date. Anything overdue appears on a staff Today screen and buzzes the phone. Enquiries arrive from a web form, from SMS and from the app into one inbox, and a customer who enquired on the web finds the conversation waiting when they install the app.",
      results: "The website and booking are live at mpcdoctor.com. The app is in TestFlight with the shop: customer and staff share one app, role-switched, alongside an owner dashboard.",
    },
    stack: ["Expo", "Express", "PostgreSQL", "Twilio", "React"],
    year: 2026,
    url: "https://mpcdoctor.com",
    screenshots: { desktop: "/work/mobile-pc-doctor-desktop.jpg", mobile: "/work/mobile-pc-doctor-mobile.jpg" },
    featured: false,
    kind: "client",
    deliveryStatus: "live",
    charity: false,
    poweredBy: null,
    domain: null,
    tagline: null,
    description: null,
    facts: [],
  },
  {
    slug: "kd-essex",
    name: "KD Essex Landscaping",
    clientName: "KD Essex Landscaping & Groundworks",
    sector: "Landscaping and groundworks",
    summary: "Research first, then a site on our BizzFlow platform that positions the firm where nobody else is.",
    brief: {
      client: "KD Essex is a landscaping, driveway and groundworks contractor in Thurrock and South Essex.",
      problem: "Every paving firm in Grays fights for the same map pack on proximity alone. KD needed a website, but first it needed a reason to be chosen.",
      built: "Before a line of the site, a research deck: competitors, reviews and searches across Thurrock and South Essex. The finding was that groundworks in the region is commercially unclaimed — the landscapers cannot dig and the groundworkers cannot finish. The plan positions KD as the one contractor who does the foundations, drainage and levels and then finishes the garden or driveway on top. The site itself runs on BizzFlow, our white-label platform for the trades: public site, enquiry capture and a CRM behind it, live in days rather than weeks.",
      results: "Research and build plan delivered as a client deck; site live on BizzFlow.",
    },
    stack: ["Research", "BizzFlow", "Google Ads"],
    year: 2026,
    url: "https://bizzflowuk.com/site/kd-essex",
    screenshots: { desktop: "/work/kd-essex-desktop.jpg", mobile: "/work/kd-essex-mobile.jpg" },
    featured: false,
    kind: "client",
    deliveryStatus: "live",
    charity: false,
    poweredBy: null,
    domain: null,
    tagline: null,
    description: null,
    facts: [],
  },
  {
    slug: "farm-pizza",
    name: "Farm Pizza",
    clientName: "Farm Pizza",
    sector: "Takeaway",
    summary: "Direct online ordering for a pizza takeaway — the first shop on our takeaway platform.",
    brief: {
      client: "Farm Pizza is a pizza takeaway trading in Basildon and Grays.",
      problem: "Orders came through aggregator apps that took a cut of every sale and kept the customer.",
      built: "A storefront with the full menu, Apple Pay and Google Pay, a kitchen pass screen and a back office. The back office does marketing as well as orders: automations that win back lapsed customers, nudge one-timers and fill quiet nights, one-off campaigns to nine customer segments, and abandoned-basket recovery. Search is built in with server-rendered menus, structured data and a page per locality. The whole thing is config-driven, so the next takeaway is a folder and a deploy.",
      results: "Live and in final testing with the shop before card payments switch on. A customer app is specified next.",
    },
    stack: ["Next.js", "PostgreSQL", "Stripe", "Resend", "Twilio", "Coolify"],
    year: 2026,
    url: "https://farm-pizza.shop",
    screenshots: { desktop: "/work/farm-pizza-desktop.jpg", mobile: "/work/farm-pizza-mobile.jpg" },
    featured: false,
    kind: "client",
    deliveryStatus: "in-testing",
    charity: false,
    poweredBy: null,
    domain: null,
    tagline: null,
    description: null,
    facts: [],
  },
  {
    slug: "amo-rendering",
    name: "AMO Rendering",
    clientName: "AMO Rendering",
    sector: "Rendering and construction",
    summary: "A full trade website, CRM and customer portal on BizzFlow, plus Google Ads that bring the work in.",
    brief: {
      client: "AMO Rendering is an external-wall rendering firm in Grays, with a sister construction business, AMO Services. Both are run by Mark from one login.",
      problem: "A rendering firm needs a site that sells five kinds of render to homeowners who do not know the difference, a way to quote fast, and adverts that do not waste money.",
      built: "AMO was the first tenant on BizzFlow, our white-label platform for the trades. The site has service pages, area pages, a gallery, reviews, case studies, a render colour visualiser and a cost calculator, with quote forms feeding a CRM pipeline. Homeowners track their job in a customer portal. We also run the Google Ads: keyword, ad and negative lists rebuilt from scratch, with a monthly report.",
      results: "Two businesses live on one platform. Google Business Profile, site and ads now agree on the same address and the same story.",
    },
    stack: ["BizzFlow", "React", "Express", "PostgreSQL", "Google Ads", "Coolify"],
    year: 2026,
    url: "https://amorendering.co.uk",
    screenshots: { desktop: "/work/amo-rendering-desktop.jpg", mobile: "/work/amo-rendering-mobile.jpg" },
    featured: false,
    kind: "client",
    deliveryStatus: "live",
    charity: false,
    poweredBy: null,
    domain: null,
    tagline: null,
    description: null,
    facts: [],
  },
  {
    slug: "amo-services",
    name: "AMO Services",
    clientName: "AMO Services",
    sector: "Construction and building",
    summary: "A construction company's site with a service page per trade and a quote form that feeds the same CRM as its sister firm.",
    brief: {
      client: "AMO Services is a construction company in Grays, established in 2011 and covering Essex and London — new builds, commercial works, home renovations, loft conversions, kitchens, electrical work and bricklaying. It is Mark Baker's second business, alongside AMO Rendering.",
      problem: "One firm doing seven quite different trades is hard to sell in a single paragraph. A homeowner searching for a loft conversion and a developer looking for groundworks want completely different pages, and neither wanted to read about the other. Both businesses also had to be run from one login rather than two systems.",
      built: "A page per trade — new builds, commercial, renovations, lofts, electrical, kitchens, bricklaying — each one landing its own searches and each one ending at the same free-quote form. The story that ties them together is the one AMO actually sells on: one team from first visit to final handover, building and electrical under one roof, a written quotation before anything starts. Enquiries land in the same BizzFlow CRM as AMO Rendering, so Mark runs both businesses from a single login.",
      results: "Two businesses, one back office. The seven trades each have somewhere to rank instead of sharing one crowded page.",
    },
    stack: ["BizzFlow", "React", "Express", "PostgreSQL", "Coolify"],
    year: 2026,
    url: "https://amoservices.co.uk",
    screenshots: { desktop: "/work/amo-services-desktop.jpg", mobile: "/work/amo-services-mobile.jpg" },
    featured: false,
    kind: "client",
    deliveryStatus: "live",
    charity: false,
    poweredBy: null,
    domain: null,
    tagline: null,
    description: null,
    facts: [],
  },
  {
    slug: "lifestyle-windows",
    name: "LifeStyle Windows",
    clientName: "Chathwell Windows Ltd",
    sector: "Windows, doors and conservatories",
    summary: "A premium glazing site with an instant estimate tool, a product page for every style and an area page for every town.",
    brief: {
      client: "LifeStyle Windows, trading as Chathwell Windows Ltd, is a family-run, FENSA-registered glazing installer working across Dagenham, East London and Essex. They have fitted windows, doors and conservatories since 2010 with their own installers rather than subcontractors.",
      problem: "Glazing is a trade with a reputation problem, and the firms that deserve better are the ones least able to show it. Homeowners compare on price alone because nothing on a typical glazing site tells them what they are getting, and every enquiry turns into a survey visit before anyone knows whether the budget is close.",
      built: "A site built to answer the question before the phone call. An instant estimate tool gives a homeowner a number without a salesperson in the room. Every product has its own page — double and triple glazing, uPVC, aluminium, sash, bay and casement windows; composite, uPVC, aluminium, bifold, patio and French doors; conservatories — so a search for one style lands on that style. Service-area pages cover Dagenham, Romford, Ilford, Barking, Redbridge, East London and Essex. The trust marks that matter in this trade sit where they are read: FENSA registration, PAS 24 and Secured by Design, the 15-year guarantee, in-house fitters and a gallery of real installs.",
      results: "Our Premium Plan client: the site, the estimate tool, the search work and the ongoing care run together, and the enquiries arrive with a budget already attached.",
    },
    stack: ["WordPress", "Divi", "Custom estimate plugin", "Google Business Profile"],
    year: 2026,
    url: "https://lifestylewindow.co.uk",
    screenshots: { desktop: "/work/lifestyle-windows-desktop.jpg", mobile: "/work/lifestyle-windows-mobile.jpg" },
    featured: true,
    kind: "client",
    deliveryStatus: "live",
    charity: false,
    poweredBy: null,
    domain: null,
    tagline: null,
    description: null,
    facts: [],
  },
];
