import { CASE_STUDY_BRIEF_DEFAULT } from "@launchos/db/schema";
import type { CaseStudySeed } from "./portfolio.js";

/**
 * The five platforms we run ourselves.
 *
 * A product has no brief and no stack — it was never a job with a client, a
 * problem and a result — and instead carries the four fields the Products page
 * lays out: the domain it is read at, a tagline, a paragraph and two to four
 * short facts. `featured` is the old `flagship`: both meant "on the home page
 * grid, four at most", so they are one column rather than two.
 */
export const PORTFOLIO_PRODUCTS: readonly CaseStudySeed[] = [
  {
    slug: "cabio",
    name: "Cabio Master Booker",
    clientName: null,
    sector: "Transport",
    summary: "The dispatch platform our own taxi firm runs on, sold to other UK operators as a subscription.",
    brief: CASE_STUDY_BRIEF_DEFAULT,
    stack: [],
    year: null,
    url: "https://cabio.cab",
    screenshots: { desktop: "/work/cabio-desktop.jpg", mobile: "/work/cabio-mobile.jpg" },
    featured: true,
    kind: "product",
    deliveryStatus: "live",
    charity: false,
    poweredBy: null,
    domain: "cabio.cab",
    tagline: "Multi-tenant taxi dispatch for UK operators.",
    description: "The dispatch platform our own taxi firm runs on, sold to other operators as a subscription. Each operator gets their own branded booking site and subdomain, a dispatch office, drivers on the app, and pricing by distance, time or fixed fare with night and zone surcharges. Built to compete with the incumbents on price and on speed.",
    facts: ["iOS and Android apps live", "Embeddable booking widget", "Card payments and subscription billing", "Runs Grays CabLine and Grays Taxis 247"],
  },
  {
    slug: "agent-zero",
    name: "Agent Zero",
    clientName: null,
    sector: "Voice AI",
    summary: "Answers a business’s calls, quotes a price and writes the booking into the back office.",
    brief: CASE_STUDY_BRIEF_DEFAULT,
    stack: [],
    year: null,
    url: "https://cabioagentzero.com",
    screenshots: { desktop: "/work/agent-zero-desktop.jpg", mobile: "/work/agent-zero-mobile.jpg" },
    featured: true,
    kind: "product",
    deliveryStatus: "live",
    charity: false,
    poweredBy: null,
    domain: "cabioagentzero.com",
    tagline: "An AI phone agent that answers and books.",
    description: "Answers a business's inbound calls, holds a natural conversation, quotes a price and writes the booking into the back office. Calls arrive over Twilio and are routed to the right business by the number dialled, so many businesses share one platform. Operators choose whether the agent answers first or their phone rings first, by schedule.",
    facts: ["Claude for the conversation", "Twilio, Deepgram and ElevenLabs", "Pushes bookings into Cabio and other dispatch systems", "Operator app on both stores"],
  },
  {
    slug: "bizzflow",
    name: "BizzFlow",
    clientName: null,
    sector: "For the trades",
    summary: "A complete website, CRM and customer portal for a trade firm, under its own brand.",
    brief: CASE_STUDY_BRIEF_DEFAULT,
    stack: [],
    year: null,
    url: "https://bizzflowuk.com",
    screenshots: { desktop: "/work/bizzflow-desktop.jpg", mobile: "/work/bizzflow-mobile.jpg" },
    featured: true,
    kind: "product",
    deliveryStatus: "live",
    charity: false,
    poweredBy: null,
    domain: "bizzflowuk.com",
    tagline: "White-label websites and CRM for the trades.",
    description: "One platform that gives a rendering, roofing or landscaping firm a complete website under their own brand, a CRM for leads, quotes and projects, and a portal where homeowners follow their job. One deployment serves every tenant, and one owner can run several businesses from a single login.",
    facts: ["Website, CRM and customer portal", "Render visualiser and cost calculator", "AMO Rendering and AMO Services live", "Google Ads run alongside"],
  },
  {
    slug: "launchos",
    name: "LaunchOS",
    clientName: null,
    sector: "Client experience",
    summary: "The portal every LaunchFlow client gets: support, plan, content, reports and invoices.",
    brief: CASE_STUDY_BRIEF_DEFAULT,
    stack: [],
    year: null,
    url: "https://os.launchflow.co.uk/sign-in",
    screenshots: { desktop: "/work/launchos-desktop.jpg", mobile: "/work/launchos-mobile.jpg" },
    featured: true,
    kind: "product",
    deliveryStatus: "live",
    charity: false,
    poweredBy: null,
    domain: "os.launchflow.co.uk",
    tagline: "The portal every LaunchFlow client gets.",
    description: "The system this agency runs on, and the website you are reading. Clients sign in to raise support cases, see the plan they are on, approve the month's content, read reports and pay invoices. Behind it, AI agents watch uptime, triage support and write content — and nothing reaches a client without a human approving it.",
    facts: ["Support, plan, content and invoices in one place", "Uptime monitoring and incidents", "Ad reports every month", "Every agent action approved by a person"],
  },
  {
    slug: "takeaway-platform",
    name: "Takeaway ordering platform",
    clientName: null,
    sector: "Food ordering",
    summary: "Direct ordering, a kitchen screen and marketing automations, without the aggregator’s cut.",
    brief: CASE_STUDY_BRIEF_DEFAULT,
    stack: [],
    year: null,
    url: "https://farm-pizza.shop",
    screenshots: { desktop: "/work/takeaway-platform-desktop.jpg", mobile: "/work/takeaway-platform-mobile.jpg" },
    featured: false,
    kind: "product",
    deliveryStatus: "in-testing",
    charity: false,
    poweredBy: null,
    domain: "farm-pizza.shop",
    tagline: "Direct ordering for takeaways, without the aggregator's cut.",
    description: "A storefront, kitchen screen and back office for a takeaway, with Apple Pay and Google Pay, automated win-back and quiet-night campaigns, abandoned-basket recovery and search built in. Everything per shop is configuration, so the next shop is a folder and a deploy. Farm Pizza is the first tenant.",
    facts: ["Next.js and Stripe", "Kitchen pass screen", "Marketing automations built in", "Customer app specified"],
  },
];
